#!/bin/bash -x

# ----------- helper functions -----------

function feedback {
  if [ $1 -eq 0 ]
  then
    zenity --info --text="$2";
  else
    zenity --warning --text="$3";
  fi
}


function list_dbs {

  mapfile -t dbs < <(ls -d */  | sed 's:/$::')

  if [[ ${#dbs[@]} -eq 0 ]]; then
      zenity --info --text="No databases found!"
      return;
  fi


  zenity --list \
    --title="Your Databases" \
    --column="Databases" \
    "${dbs[@]}"
}


function create_db {
  db_name=$(zenity --entry --title="Input required" --text="Enter Database Name:")


  if [[ -d "$db_name" ]]; then
    zenity --warning --text="Database '$db_name' already exists!"
    return
  fi

  mkdir "$db_name"
 
 feedback $? "Database '$db_name' created  successfully!" "Failed to create database"
}


function connect_db {

  mapfile -t dbs < <(ls -d */  | sed 's:/$::')

  if [[ ${#dbs[@]} -eq 0 ]]; then
      zenity --info --text="No databases found!"
      return
  fi

  target_db=$(zenity --list \
    --title="Please select a database to connect" \
    --column="Databases" \
    "${dbs[@]}")

  [[ -z "$target_db" ]] && return

  
  . ./db "$target_db"
}


function drop_db {

  mapfile -t dbs < <(ls -d */ | sed 's:/$::')

  if [[ ${#dbs[@]} -eq 0 ]]; then
    zenity --info --text="No databases found to drop!"
    return
  fi

  target_db=$(zenity --list \
    --title="Please select a database to drop" \
    --column="Databases" \
    "${dbs[@]}")



  zenity --question --text="Are you sure you want to delete '$target_db'?"
  [[ $? -ne 0 ]] && return

  rm -rf "$target_db"
  feedback $? "Database dropped successfully" "Failed to drop database"
}

# ----------- Entry Point Function -----------
function main {
  while true; do
    option=$(zenity --list \
      --title="Welcome to DBMS App, Please select an option to start" \
      --column="Options" \
      "Create Database" \
      "List Databases" \
      "Connect to Database" \
      "Drop Database" \
      "Exit")

    case $option in
      "Create Database")
        create_db
        ;;
      "List Databases")
        list_dbs
        ;;
      "Connect to Database")
        connect_db
        ;;
      "Drop Database")
        drop_db
        ;;
      "Exit")
        exit 0
        ;;
      *)
        if [ $? -eq 1 ]
        then
         zenity --warning --text="Invalid choice, please select again";
        fi
        ;;
    esac
  done
}

main
