#!/bin/bash -x

# ----------- helper functions -----------

function feedback {
  if [ $1 -eq 0 ]
  then
    zenity --info --text="$2";
  else
    zenity --warning --text="$3";
  fi
}

function get_dbs_count {
  all_dbs=(*/);

  if [[ $all_dbs == "*/" ]]
  then
    zenity --info --text="No databases founded"
    exit 1;
  fi

  dbs_count=${#all_dbs[@]};
  return $dbs_count;
}

# ----------- Features Functions -----------

function list_dbs {
  dbs=` ls -d */ | sed 's:/$::' `
  zenity --list --title="Your Databases" --column="Databases" $dbs
}

function create_db {
  db_name=${USER_INPUT=$(zenity --entry --title="Input required" --text="Enter DataBase Name:")};
  mkdir "$db_name";

  feedback $? "Database created successfully" "Failed to create database";
}

function connect_db {
  get_dbs_count;
  dbs_count=$?;

  dbs=` ls -d */ | sed 's:/$::' `
  target_db=` zenity --list --title="Please select an option to start" --column="Databases" $dbs `;

  . ./db "$target_db";
}

function drop_db {
  get_dbs_count;
  dbs_count=$?;

  dbs=` ls -d */ | sed 's:/$::' `
  target_db=` zenity --list --title="Please select an option to start" --column="Databases" $dbs `;

  rm -rf $target_db;
  feedback $? "Database dropped successfully" "Failed to drop database";
}

# ----------- Entry Point Function -----------
function main {
  while true; do
    option=$(zenity --list \
      --title="Welcome to DBMS App, Please select an option to start" \
      --column="Options" \
      "Create Database" \
      "List Databases" \
      "Connect to Database" \
      "Drop Database" \
      "Exit")

    case $option in
      "Create Database")
        create_db
        ;;
      "List Databases")
        list_dbs
        ;;
      "Connect to Database")
        connect_db
        ;;
      "Drop Database")
        drop_db
        ;;
      "Exit")
        exit 0
        ;;
      *)
        zenity --warning --text="Invalid choice, please select again"
        ;;
    esac
  done
}

main
